GEMINI_API_KEY = ""
BOT_QQ_ID = ""
EVENT_STREAM_URL = ""
SEND_MESSAGE_URL = ""
GET_GROUP_MSG_HISTORY_URL = ""

ENABLE_VISION = False
MAX_MESSAGES_HISTORY = 800

# API Server Configuration
API_PORT = 8000